/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Accounts */
        get: operations["accounts_api_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Activity Calendar */
        get: operations["activity_calendar_api_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Local Context */
        get: operations["local_context_api_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/report-context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report Context */
        get: operations["report_context_api_report_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wrapped": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Wrapped */
        get: operations["wrapped_api_wrapped_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alerts */
        get: operations["alerts_api_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service Status */
        get: operations["service_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weekly-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Weekly Summary */
        post: operations["weekly_summary_api_weekly_summary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/concierge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Concierge */
        get: operations["concierge_api_concierge_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Findings
         * @description The stored snapshot; recomputed only after the store changes (A-092).
         */
        get: operations["findings_api_findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Analysis
         * @description Recompute now, whatever the snapshot says.
         */
        post: operations["run_analysis_api_analysis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/findings/{finding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Finding Detail
         * @description One finding, for the deep-linkable finding modal (A-046).
         */
        get: operations["finding_detail_api_findings__finding_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/findings/{finding_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss Finding */
        post: operations["dismiss_finding_api_findings__finding_id__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily */
        get: operations["daily_api_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hourly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hourly */
        get: operations["hourly_api_hourly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/breakdown/{dim}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Breakdown */
        get: operations["breakdown_api_breakdown__dim__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sessions List */
        get: operations["sessions_list_api_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Detail */
        get: operations["session_detail_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session-facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Facets */
        get: operations["session_facets_api_session_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Blocks */
        get: operations["blocks_api_blocks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/codex-quota": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Codex Quota Endpoint
         * @description Codex plan limits read from local rollouts: a ChatGPT plan, never Anthropic's.
         */
        get: operations["codex_quota_endpoint_api_codex_quota_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/copilot-quota": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Copilot Quota Endpoint
         * @description Copilot premium-request use from its local cache: a GitHub plan, never Anthropic's.
         */
        get: operations["copilot_quota_endpoint_api_copilot_quota_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quota": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quota Endpoint */
        get: operations["quota_endpoint_api_quota_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reconciliation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reconciliation
         * @description Why these numbers differ from Claude's own Stats (A-116, A-125).
         *
         *     Date filters apply. Source, project and model do not: the Stats have none.
         */
        get: operations["reconciliation_api_reconciliation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync */
        post: operations["sync_api_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/harvest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Harvest */
        post: operations["harvest_api_harvest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export */
        get: operations["export_api_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountsOut */
        AccountsOut: {
            /** Selected */
            selected: string;
            /** Accounts */
            accounts: string[];
        };
        /** ActiveBlockOut */
        ActiveBlockOut: {
            /** Start */
            start: string;
            /** End */
            end: string;
            /** Tokens */
            tokens: number;
            /** Cost Usd */
            cost_usd: number;
            /** Tokens Per Minute */
            tokens_per_minute: number;
            /** Projected Tokens */
            projected_tokens: number;
            /** Projected Cost Usd */
            projected_cost_usd: number;
        };
        /** ActivityOut */
        ActivityOut: {
            /** Days */
            days: {
                [key: string]: number;
            };
            /** Current Streak */
            current_streak: number;
            /** Longest Streak */
            longest_streak: number;
            /** Truncated */
            truncated: boolean;
        };
        /** AlertBlockOut */
        AlertBlockOut: {
            /** Tokens Per Minute */
            tokens_per_minute: number;
            /** Cost Per Minute */
            cost_per_minute: number;
        };
        /** AlertOut */
        AlertOut: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "serious";
            /** Title */
            title: string;
            /** Detail */
            detail: string;
            /** Created At */
            created_at: string;
        };
        /** AlertsOut */
        AlertsOut: {
            /** Alerts */
            alerts: components["schemas"]["AlertOut"][];
            /** New Count */
            new_count: number;
            active_block: components["schemas"]["AlertBlockOut"] | null;
            /** Notes */
            notes: string[];
        };
        /** AnalysisOut */
        AnalysisOut: {
            /** Findings */
            findings: components["schemas"]["FindingOut"][];
            /** Notes */
            notes: string[];
            /**
             * Anomaly Notes
             * @default []
             */
            anomaly_notes: string[];
            /** Analyzed At */
            analyzed_at: string;
        };
        /** BandOut */
        BandOut: {
            /** P10 */
            p10: number;
            /** P50 */
            p50: number;
            /** P90 */
            p90: number;
        };
        /** BlockOut */
        BlockOut: {
            provenance?: components["schemas"]["ProvenanceOut"] | null;
            /** Start */
            start: string;
            /** End */
            end: string;
            /** Is Active */
            is_active: boolean;
            /** Tokens */
            tokens: number;
            /** Cost Usd */
            cost_usd: number;
            /** Tokens Per Minute */
            tokens_per_minute: number;
            /** Models */
            models: string[];
        };
        /** BucketOut */
        BucketOut: {
            /** Responses */
            responses: number;
            /** Input */
            input: number;
            /** Cache Write 5M */
            cache_write_5m: number;
            /** Cache Write 1H */
            cache_write_1h: number;
            /** Cache Read */
            cache_read: number;
            /** Output */
            output: number;
            /** Thinking */
            thinking: number;
            /**
             * Web Fetch
             * @default 0
             */
            web_fetch: number;
            /**
             * Code Execution
             * @default 0
             */
            code_execution: number;
            /**
             * Code Execution Cost
             * @default not_used
             * @enum {string}
             */
            code_execution_cost: "unavailable" | "not_used";
            /**
             * Nonstandard Iterations
             * @default 0
             */
            nonstandard_iterations: number;
            /**
             * Context Premium Unknown
             * @default 0
             */
            context_premium_unknown: number;
            /** Web Searches */
            web_searches: number;
            /** Cost Usd */
            cost_usd: number;
            /**
             * Unpriced
             * @default 0
             */
            unpriced: number;
        };
        /** ConciergeOut */
        ConciergeOut: {
            /** Project */
            project: string;
            /** Text */
            text: string;
            /** Notes */
            notes: string[];
        };
        /** CountOut */
        CountOut: {
            /** N */
            n: number;
        };
        /** CoverageOut */
        CoverageOut: {
            /** Sources */
            sources: components["schemas"]["SourceCoverageOut"][];
            /** Gaps */
            gaps: components["schemas"]["GapOut"][];
            /** Dropped Records */
            dropped_records: {
                [key: string]: number;
            };
        };
        /** DedupedFiguresOut */
        DedupedFiguresOut: {
            /** Responses */
            responses: number;
            /** Input Output Tokens */
            input_output_tokens: number;
            /** All Tokens */
            all_tokens: number;
            /** Sessions */
            sessions: number;
        };
        /** DismissFindingIn */
        DismissFindingIn: {
            /**
             * Dismissed
             * @default true
             */
            dismissed: boolean;
        };
        /** DismissFindingOut */
        DismissFindingOut: {
            /** Id */
            id: string;
            /** Dismissed */
            dismissed: boolean;
        };
        /** FindingOut */
        FindingOut: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "anomaly" | "cache" | "tip" | "waste" | "peak" | "context";
            /** Rule */
            rule: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "urgent";
            /** Subject */
            subject: string;
            /** Day */
            day: string | null;
            /** Title */
            title: string;
            /** Detail */
            detail: string;
            /** Coverage */
            coverage: string;
            /** Session Id */
            session_id: string | null;
            /** Savings Usd */
            savings_usd: number | null;
            /** Metrics */
            metrics: {
                [key: string]: number | string | null;
            };
            /** Dismissed */
            dismissed: boolean;
            /** Created At */
            created_at: string;
        };
        /** GapOut */
        GapOut: {
            /** Start */
            start: string;
            /** End */
            end: string;
            /** Days */
            days: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HarvestEnvelope
         * @description A session listing wrapped as `{"data": [...]}` or `{"ccr": ...}`.
         */
        HarvestEnvelope: {
            /** Data */
            data?: {
                [key: string]: unknown;
            }[] | null;
            /** Ccr */
            ccr?: {
                [key: string]: unknown;
            }[] | {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /** HarvestResultOut */
        HarvestResultOut: {
            /** Written */
            written: number;
            /** Skipped */
            skipped: number;
            /**
             * Rejected No Id
             * @default 0
             */
            rejected_no_id: number;
            /**
             * Skipped Environment
             * @default 0
             */
            skipped_environment: number;
        };
        /** HealthOut */
        HealthOut: {
            turns: components["schemas"]["StoreTurnsOut"];
            cloud: components["schemas"]["StoreCloudOut"];
            /** Cloud By Surface */
            cloud_by_surface: components["schemas"]["SurfaceCountOut"][];
            prompts: components["schemas"]["CountOut"];
            /** Last Harvest */
            last_harvest: string | null;
            /** Last Sync */
            last_sync: string | null;
            coverage: components["schemas"]["CoverageOut"];
            /** Note */
            note: string;
        };
        /** LocalContextOut */
        LocalContextOut: {
            /** Session */
            session: string;
            /** Source */
            source: string;
            /** Used Tokens */
            used_tokens: number;
            /** Max Tokens */
            max_tokens: number;
            /**
             * Severity
             * @enum {string}
             */
            severity: "warning" | "urgent";
            /** Snapshot At */
            snapshot_at: string;
        };
        /** PlanComparisonOut */
        PlanComparisonOut: {
            /** Period Start */
            period_start: string;
            /** Period End */
            period_end: string;
            /** Local Cost Usd */
            local_cost_usd: number;
            /** Monthly Plan Usd */
            monthly_plan_usd: number;
            /** Multiple */
            multiple: number | null;
            /** Unpriced */
            unpriced: number;
        };
        /** ProvenanceOut */
        ProvenanceOut: {
            /**
             * Usage
             * @enum {string}
             */
            usage: "official" | "computed_local" | "cloud_reported" | "estimate";
            /**
             * Cost
             * @enum {string}
             */
            cost: "official" | "computed_local" | "cloud_reported" | "estimate";
            /** Scope */
            scope: string;
            /** As Of */
            as_of: string | null;
        };
        /** QuotaOut */
        QuotaOut: {
            provenance?: components["schemas"]["ProvenanceOut"] | null;
            /** Source */
            source: string;
            /** Fetched At */
            fetched_at: string;
            /** Windows */
            windows: components["schemas"]["WindowOut"][];
            /**
             * Recent
             * @default []
             */
            recent: components["schemas"]["QuotaSampleOut"][];
            /**
             * Notes
             * @default []
             */
            notes: string[];
        };
        /** QuotaSampleOut */
        QuotaSampleOut: {
            /** Ts */
            ts: string;
            /** Key */
            key: string;
            /** Scope */
            scope: string;
            /** Utilization */
            utilization: number;
            /** Resets At */
            resets_at: string | null;
            /** Source */
            source: string;
        };
        /** ReconciliationOut */
        ReconciliationOut: {
            /** Source */
            source: string;
            deduped: components["schemas"]["DedupedFiguresOut"];
            stats_equivalent: components["schemas"]["StatsFiguresOut"];
            /** Token Ratio */
            token_ratio: number | null;
            /** Reasons */
            reasons: string[];
            /** Session Definition */
            session_definition: string;
        };
        /** ReportContextOut */
        ReportContextOut: {
            /** Today */
            today: string;
            /** Timezone */
            timezone: string;
            /** Day Start Hour */
            day_start_hour: number;
            /** As Of */
            as_of: string | null;
        };
        /** ServiceStatusOut */
        ServiceStatusOut: {
            /** Indicator */
            indicator: string;
            /** Description */
            description: string;
            /** Url */
            url: string;
        };
        /** SessionDetailOut */
        SessionDetailOut: {
            provenance?: components["schemas"]["ProvenanceOut"] | null;
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Surface */
            surface: string | null;
            /** Project */
            project: string | null;
            /** Model */
            model: string | null;
            /** Started */
            started: string | null;
            /** Ended */
            ended: string | null;
            /** Tokens */
            tokens: number;
            /** Cost */
            cost: number;
            /** Harvested */
            harvested: boolean;
            /** Cursor */
            cursor?: string | null;
            /**
             * Unpriced Turns
             * @default 0
             */
            unpriced_turns: number;
            /** Context Used */
            context_used?: number | null;
            /** Context Max */
            context_max?: number | null;
            /** Turns */
            turns: components["schemas"]["TurnOut"][];
        };
        /** SessionFacetsOut */
        SessionFacetsOut: {
            /** Sources */
            sources: string[];
            /** Projects */
            projects: string[];
            /** Models */
            models: string[];
        };
        /** SessionOut */
        SessionOut: {
            provenance?: components["schemas"]["ProvenanceOut"] | null;
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Surface */
            surface: string | null;
            /** Project */
            project: string | null;
            /** Model */
            model: string | null;
            /** Started */
            started: string | null;
            /** Ended */
            ended: string | null;
            /** Tokens */
            tokens: number;
            /** Cost */
            cost: number;
            /** Harvested */
            harvested: boolean;
            /** Cursor */
            cursor?: string | null;
            /**
             * Unpriced Turns
             * @default 0
             */
            unpriced_turns: number;
            /** Context Used */
            context_used?: number | null;
            /** Context Max */
            context_max?: number | null;
        };
        /** SourceCoverageOut */
        SourceCoverageOut: {
            /** Source */
            source: string;
            /** Files */
            files: number;
            /** First Day */
            first_day: string | null;
            /** Last Day */
            last_day: string | null;
        };
        /** StatsFiguresOut */
        StatsFiguresOut: {
            /** Messages */
            messages: number;
            /** Tokens */
            tokens: number;
            /** Sessions */
            sessions: number;
        };
        /** StoreCloudOut */
        StoreCloudOut: {
            /** N */
            n: number;
            /** Cost */
            cost: number | null;
        };
        /** StoreTurnsOut */
        StoreTurnsOut: {
            /** N */
            n: number;
            /** Lo */
            lo: string | null;
            /** Hi */
            hi: string | null;
            /** Cost */
            cost: number | null;
        };
        /** SummaryOut */
        SummaryOut: {
            provenance?: components["schemas"]["ProvenanceOut"] | null;
            plan_comparison?: components["schemas"]["PlanComparisonOut"] | null;
            total: components["schemas"]["BucketOut"];
            /** By Day */
            by_day: {
                [key: string]: components["schemas"]["BucketOut"];
            };
            /** By Model */
            by_model: {
                [key: string]: components["schemas"]["BucketOut"];
            };
            /** By Source */
            by_source: {
                [key: string]: components["schemas"]["BucketOut"];
            };
            /** By Project */
            by_project: {
                [key: string]: components["schemas"]["BucketOut"];
            };
            /** By Day Model */
            by_day_model: {
                [key: string]: components["schemas"]["BucketOut"];
            };
            /** By Hour */
            by_hour: {
                [key: string]: components["schemas"]["BucketOut"];
            };
            /** Sessions */
            sessions: number;
            /** Unknown Models */
            unknown_models: string[];
            /** Restored Days */
            restored_days: string[];
            /** Cache Hit Rate */
            cache_hit_rate: number;
            active_block?: components["schemas"]["ActiveBlockOut"] | null;
        };
        /** SurfaceCountOut */
        SurfaceCountOut: {
            /** Surface */
            surface: string | null;
            /** N */
            n: number;
            /** Cost */
            cost: number | null;
        };
        /** SyncResultOut */
        SyncResultOut: {
            /** Parsed */
            parsed: number;
            /** Skipped */
            skipped: number;
            /** Turns */
            turns: number;
            /** Duplicates */
            duplicates: number;
            /** Prompts */
            prompts: number;
            /**
             * Unreadable
             * @default 0
             */
            unreadable: number;
        };
        /** TurnOut */
        TurnOut: {
            /** Msg Id */
            msg_id: string;
            /** Request Id */
            request_id: string;
            /** Ts */
            ts: string;
            /** Day */
            day: string;
            /** Source */
            source: string;
            /** Project */
            project: string;
            /** Model */
            model: string;
            /** Input */
            input: number;
            /** Cache 5M */
            cache_5m: number;
            /** Cache 1H */
            cache_1h: number;
            /** Cache Read */
            cache_read: number;
            /** Output */
            output: number;
            /** Thinking */
            thinking: number;
            /** Web Search */
            web_search: number;
            /** Sidechain */
            sidechain: number;
            /** Fast */
            fast: number;
            /** Geo */
            geo: string | null;
            /** Cost */
            cost: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeeklySummaryOut */
        WeeklySummaryOut: {
            /** Status */
            status: string;
            /** Text */
            text: string | null;
            /** Detail */
            detail: string;
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
        };
        /** WindowOut */
        WindowOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Scope */
            scope: string;
            /** Source */
            source: string;
            /** Utilization */
            utilization: number;
            /** Resets At */
            resets_at: string | null;
            /** Pace Delta */
            pace_delta?: number | null;
            /** Elapsed Pct */
            elapsed_pct?: number | null;
            band?: components["schemas"]["BandOut"] | null;
            /** Note */
            note?: string | null;
        };
        /** WrappedModelMonthOut */
        WrappedModelMonthOut: {
            /** Month */
            month: string;
            /** Model */
            model: string;
            /** Cost Usd */
            cost_usd: number;
            /** Tokens */
            tokens: number;
        };
        /** WrappedOut */
        WrappedOut: {
            /**
             * Provenance By Source
             * @default {}
             */
            provenance_by_source: {
                [key: string]: components["schemas"]["ProvenanceOut"];
            };
            /** Year */
            year: number;
            /** Timezone */
            timezone: string;
            local_summary: components["schemas"]["SummaryOut"];
            /** Stored Cost Usd */
            stored_cost_usd: number;
            /** Harvested Cost Usd */
            harvested_cost_usd: number;
            /** Stored Tokens */
            stored_tokens: number;
            /** Stored Sessions */
            stored_sessions: number;
            /** Unpriced Turns */
            unpriced_turns: number;
            /** Annual Plan Usd */
            annual_plan_usd: number | null;
            /** Api Equivalent Multiple */
            api_equivalent_multiple: number | null;
            /** Busiest Day */
            busiest_day: string | null;
            /** Busiest Hour */
            busiest_hour: number | null;
            /** Longest Streak */
            longest_streak: number;
            /** Top Projects */
            top_projects: components["schemas"]["WrappedProjectOut"][];
            /** Model Months */
            model_months: components["schemas"]["WrappedModelMonthOut"][];
            biggest_session: components["schemas"]["WrappedSessionOut"] | null;
            /** Cache Savings Usd */
            cache_savings_usd: number | null;
            /** Notes */
            notes: string[];
        };
        /** WrappedProjectOut */
        WrappedProjectOut: {
            /** Name */
            name: string;
            /** Cost Usd */
            cost_usd: number;
            /** Tokens */
            tokens: number;
        };
        /** WrappedSessionOut */
        WrappedSessionOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Cost Usd */
            cost_usd: number;
            /** Tokens */
            tokens: number;
            /** Harvested */
            harvested: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    accounts_api_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountsOut"];
                };
            };
        };
    };
    activity_calendar_api_activity_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityOut"];
                };
            };
        };
    };
    local_context_api_context_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalContextOut"][];
                };
            };
        };
    };
    report_context_api_report_context_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportContextOut"];
                };
            };
        };
    };
    wrapped_api_wrapped_get: {
        parameters: {
            query?: {
                year?: number | null;
                from?: string | null;
                to?: string | null;
                source?: "all" | "claude" | "claude-code" | "cowork" | "codex" | "copilot" | "antigravity" | "web";
                project?: string | null;
                model?: string | null;
                metric?: "cost" | "tokens";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WrappedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alerts_api_alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertsOut"];
                };
            };
        };
    };
    service_status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceStatusOut"] | null;
                };
            };
        };
    };
    weekly_summary_api_weekly_summary_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklySummaryOut"];
                };
            };
        };
    };
    concierge_api_concierge_get: {
        parameters: {
            query: {
                project: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConciergeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    findings_api_findings_get: {
        parameters: {
            query?: {
                kind?: ("anomaly" | "cache" | "tip" | "waste" | "peak" | "context") | null;
                severity?: ("info" | "warning" | "urgent") | null;
                include_dismissed?: boolean;
                from?: string | null;
                to?: string | null;
                source?: "all" | "claude" | "claude-code" | "cowork" | "codex" | "copilot" | "antigravity" | "web";
                project?: string | null;
                model?: string | null;
                metric?: "cost" | "tokens";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_analysis_api_analysis_post: {
        parameters: {
            query?: {
                kind?: ("anomaly" | "cache" | "tip" | "waste" | "peak" | "context") | null;
                severity?: ("info" | "warning" | "urgent") | null;
                include_dismissed?: boolean;
                from?: string | null;
                to?: string | null;
                source?: "all" | "claude" | "claude-code" | "cowork" | "codex" | "copilot" | "antigravity" | "web";
                project?: string | null;
                model?: string | null;
                metric?: "cost" | "tokens";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finding_detail_api_findings__finding_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingOut"];
                };
            };
            /** @description No such finding */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_finding_api_findings__finding_id__dismiss_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DismissFindingIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DismissFindingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_summary_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                source?: "all" | "claude" | "claude-code" | "cowork" | "codex" | "copilot" | "antigravity" | "web";
                project?: string | null;
                model?: string | null;
                metric?: "cost" | "tokens";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daily_api_daily_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                source?: "all" | "claude" | "claude-code" | "cowork" | "codex" | "copilot" | "antigravity" | "web";
                project?: string | null;
                model?: string | null;
                metric?: "cost" | "tokens";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["BucketOut"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hourly_api_hourly_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                source?: "all" | "claude" | "claude-code" | "cowork" | "codex" | "copilot" | "antigravity" | "web";
                project?: string | null;
                model?: string | null;
                metric?: "cost" | "tokens";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["BucketOut"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    breakdown_api_breakdown__dim__get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                source?: "all" | "claude" | "claude-code" | "cowork" | "codex" | "copilot" | "antigravity" | "web";
                project?: string | null;
                model?: string | null;
                metric?: "cost" | "tokens";
            };
            header?: never;
            path: {
                dim: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["BucketOut"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sessions_list_api_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                q?: string | null;
                from?: string | null;
                to?: string | null;
                source?: "all" | "claude" | "claude-code" | "cowork" | "codex" | "copilot" | "antigravity" | "web";
                project?: string | null;
                model?: string | null;
                metric?: "cost" | "tokens";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_detail_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_facets_api_session_facets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionFacetsOut"];
                };
            };
        };
    };
    blocks_api_blocks_get: {
        parameters: {
            query?: {
                limit?: number;
                from?: string | null;
                to?: string | null;
                source?: "all" | "claude" | "claude-code" | "cowork" | "codex" | "copilot" | "antigravity" | "web";
                project?: string | null;
                model?: string | null;
                metric?: "cost" | "tokens";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    codex_quota_endpoint_api_codex_quota_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotaOut"] | null;
                };
            };
        };
    };
    copilot_quota_endpoint_api_copilot_quota_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotaOut"] | null;
                };
            };
        };
    };
    quota_endpoint_api_quota_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                source?: "all" | "claude" | "claude-code" | "cowork" | "codex" | "copilot" | "antigravity" | "web";
                project?: string | null;
                model?: string | null;
                metric?: "cost" | "tokens";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotaOut"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reconciliation_api_reconciliation_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                source?: "all" | "claude" | "claude-code" | "cowork" | "codex" | "copilot" | "antigravity" | "web";
                project?: string | null;
                model?: string | null;
                metric?: "cost" | "tokens";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconciliationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    sync_api_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description With `Accept: application/x-ndjson`, one `{done, total}` line per batch, then the result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResultOut"];
                    "application/x-ndjson": unknown;
                };
            };
            /** @description A sync is already running */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    harvest_api_harvest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                }[] | components["schemas"]["HarvestEnvelope"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HarvestResultOut"];
                };
            };
            /** @description Not a session listing */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Body larger than 20 MiB */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_api_export_get: {
        parameters: {
            query?: {
                format?: "json" | "csv";
                from?: string | null;
                to?: string | null;
                source?: "all" | "claude" | "claude-code" | "cowork" | "codex" | "copilot" | "antigravity" | "web";
                project?: string | null;
                model?: string | null;
                metric?: "cost" | "tokens";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daily rows by model as CSV, or the summary as JSON. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                    "text/csv": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
