/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily */
        get: operations["daily_api_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hourly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hourly */
        get: operations["hourly_api_hourly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/breakdown/{dim}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Breakdown */
        get: operations["breakdown_api_breakdown__dim__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sessions List */
        get: operations["sessions_list_api_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Detail */
        get: operations["session_detail_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Blocks */
        get: operations["blocks_api_blocks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quota": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quota Endpoint */
        get: operations["quota_endpoint_api_quota_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync */
        post: operations["sync_api_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/harvest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Harvest */
        post: operations["harvest_api_harvest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export */
        get: operations["export_api_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Legacy Usage */
        get: operations["legacy_usage_api_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dataset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Legacy Dataset */
        get: operations["legacy_dataset_api_dataset_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/index.html": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Legacy Page */
        get: operations["legacy_page_index_html_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Legacy Page */
        get: operations["legacy_page__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveBlockOut */
        ActiveBlockOut: {
            /** Start */
            start: string;
            /** End */
            end: string;
            /** Tokens */
            tokens: number;
            /** Cost Usd */
            cost_usd: number;
            /** Tokens Per Minute */
            tokens_per_minute: number;
            /** Projected Tokens */
            projected_tokens: number;
            /** Projected Cost Usd */
            projected_cost_usd: number;
        };
        /** BlockOut */
        BlockOut: {
            /** Start */
            start: string;
            /** End */
            end: string;
            /** Is Active */
            is_active: boolean;
            /** Tokens */
            tokens: number;
            /** Cost Usd */
            cost_usd: number;
            /** Tokens Per Minute */
            tokens_per_minute: number;
            /** Models */
            models: string[];
        };
        /** BucketOut */
        BucketOut: {
            /** Responses */
            responses: number;
            /** Input */
            input: number;
            /** Cache Write 5M */
            cache_write_5m: number;
            /** Cache Write 1H */
            cache_write_1h: number;
            /** Cache Read */
            cache_read: number;
            /** Output */
            output: number;
            /** Thinking */
            thinking: number;
            /** Web Searches */
            web_searches: number;
            /** Cost Usd */
            cost_usd: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HarvestResultOut */
        HarvestResultOut: {
            /** Written */
            written: number;
            /** Skipped */
            skipped: number;
        };
        /** HealthOut */
        HealthOut: {
            /** Turns */
            turns: {
                [key: string]: unknown;
            };
            /** Cloud */
            cloud: {
                [key: string]: unknown;
            };
            /** Cloud By Surface */
            cloud_by_surface: {
                [key: string]: unknown;
            }[];
            /** Prompts */
            prompts: {
                [key: string]: unknown;
            };
            /** Last Harvest */
            last_harvest: string | null;
            /** Note */
            note: string;
        };
        /** QuotaOut */
        QuotaOut: {
            /** Source */
            source: string;
            /** Fetched At */
            fetched_at: string;
            /** Windows */
            windows: components["schemas"]["WindowOut"][];
        };
        /** SessionDetailOut */
        SessionDetailOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Surface */
            surface: string | null;
            /** Project */
            project: string | null;
            /** Model */
            model: string | null;
            /** Started */
            started: string | null;
            /** Ended */
            ended: string | null;
            /** Tokens */
            tokens: number;
            /** Cost */
            cost: number;
            /** Harvested */
            harvested: boolean;
            /** Turns */
            turns: {
                [key: string]: unknown;
            }[];
        };
        /** SessionOut */
        SessionOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Surface */
            surface: string | null;
            /** Project */
            project: string | null;
            /** Model */
            model: string | null;
            /** Started */
            started: string | null;
            /** Ended */
            ended: string | null;
            /** Tokens */
            tokens: number;
            /** Cost */
            cost: number;
            /** Harvested */
            harvested: boolean;
        };
        /** SummaryOut */
        SummaryOut: {
            total: components["schemas"]["BucketOut"];
            /** By Day */
            by_day: {
                [key: string]: components["schemas"]["BucketOut"];
            };
            /** By Model */
            by_model: {
                [key: string]: components["schemas"]["BucketOut"];
            };
            /** By Source */
            by_source: {
                [key: string]: components["schemas"]["BucketOut"];
            };
            /** By Project */
            by_project: {
                [key: string]: components["schemas"]["BucketOut"];
            };
            /** By Day Model */
            by_day_model: {
                [key: string]: components["schemas"]["BucketOut"];
            };
            /** By Hour */
            by_hour: {
                [key: string]: components["schemas"]["BucketOut"];
            };
            /** Sessions */
            sessions: number;
            /** Unknown Models */
            unknown_models: string[];
            /** Restored Days */
            restored_days: string[];
            /** Cache Hit Rate */
            cache_hit_rate: number;
            active_block?: components["schemas"]["ActiveBlockOut"] | null;
        };
        /** SyncResultOut */
        SyncResultOut: {
            /** Parsed */
            parsed: number;
            /** Skipped */
            skipped: number;
            /** Turns */
            turns: number;
            /** Duplicates */
            duplicates: number;
            /** Prompts */
            prompts: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WindowOut */
        WindowOut: {
            /** Label */
            label: string;
            /** Utilization */
            utilization: number;
            /** Resets At */
            resets_at: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    summary_api_summary_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                source?: string;
                project?: string | null;
                model?: string | null;
                metric?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daily_api_daily_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                source?: string;
                project?: string | null;
                model?: string | null;
                metric?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["BucketOut"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hourly_api_hourly_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                source?: string;
                project?: string | null;
                model?: string | null;
                metric?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["BucketOut"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    breakdown_api_breakdown__dim__get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                source?: string;
                project?: string | null;
                model?: string | null;
                metric?: string;
            };
            header?: never;
            path: {
                dim: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["BucketOut"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sessions_list_api_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                from?: string | null;
                to?: string | null;
                source?: string;
                project?: string | null;
                model?: string | null;
                metric?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_detail_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    blocks_api_blocks_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                source?: string;
                project?: string | null;
                model?: string | null;
                metric?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quota_endpoint_api_quota_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                source?: string;
                project?: string | null;
                model?: string | null;
                metric?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotaOut"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    sync_api_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResultOut"];
                };
            };
        };
    };
    harvest_api_harvest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HarvestResultOut"];
                };
            };
        };
    };
    export_api_export_get: {
        parameters: {
            query?: {
                format?: string;
                from?: string | null;
                to?: string | null;
                source?: string;
                project?: string | null;
                model?: string | null;
                metric?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    legacy_usage_api_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    legacy_dataset_api_dataset_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    legacy_page_index_html_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    legacy_page__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
}
