/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/wrapped": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Wrapped */
        get: operations["wrapped_api_wrapped_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alerts */
        get: operations["alerts_api_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service Status */
        get: operations["service_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weekly-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Weekly Summary */
        post: operations["weekly_summary_api_weekly_summary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/concierge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Concierge */
        get: operations["concierge_api_concierge_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Findings */
        post: operations["findings_api_analysis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Findings */
        get: operations["findings_api_findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/findings/{finding_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss Finding */
        post: operations["dismiss_finding_api_findings__finding_id__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily */
        get: operations["daily_api_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hourly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hourly */
        get: operations["hourly_api_hourly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/breakdown/{dim}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Breakdown */
        get: operations["breakdown_api_breakdown__dim__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sessions List */
        get: operations["sessions_list_api_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Detail */
        get: operations["session_detail_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session-facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Facets */
        get: operations["session_facets_api_session_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Blocks */
        get: operations["blocks_api_blocks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quota": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quota Endpoint */
        get: operations["quota_endpoint_api_quota_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync */
        post: operations["sync_api_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/harvest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Harvest */
        post: operations["harvest_api_harvest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export */
        get: operations["export_api_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Legacy Usage */
        get: operations["legacy_usage_api_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dataset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Legacy Dataset */
        get: operations["legacy_dataset_api_dataset_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/index.html": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Legacy Page */
        get: operations["legacy_page_index_html_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Legacy Page */
        get: operations["legacy_page__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveBlockOut */
        ActiveBlockOut: {
            /** Start */
            start: string;
            /** End */
            end: string;
            /** Tokens */
            tokens: number;
            /** Cost Usd */
            cost_usd: number;
            /** Tokens Per Minute */
            tokens_per_minute: number;
            /** Projected Tokens */
            projected_tokens: number;
            /** Projected Cost Usd */
            projected_cost_usd: number;
        };
        /** AlertBlockOut */
        AlertBlockOut: {
            /** Tokens Per Minute */
            tokens_per_minute: number;
            /** Cost Per Minute */
            cost_per_minute: number;
        };
        /** AlertOut */
        AlertOut: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Detail */
            detail: string;
            /** Created At */
            created_at: string;
        };
        /** AlertsOut */
        AlertsOut: {
            /** Alerts */
            alerts: components["schemas"]["AlertOut"][];
            /** New Count */
            new_count: number;
            active_block: components["schemas"]["AlertBlockOut"] | null;
            /** Notes */
            notes: string[];
        };
        /** AnalysisOut */
        AnalysisOut: {
            /** Findings */
            findings: components["schemas"]["FindingOut"][];
            /** Notes */
            notes: string[];
            /** Analyzed At */
            analyzed_at: string;
        };
        /** BlockOut */
        BlockOut: {
            /** Start */
            start: string;
            /** End */
            end: string;
            /** Is Active */
            is_active: boolean;
            /** Tokens */
            tokens: number;
            /** Cost Usd */
            cost_usd: number;
            /** Tokens Per Minute */
            tokens_per_minute: number;
            /** Models */
            models: string[];
        };
        /** BucketOut */
        BucketOut: {
            /** Responses */
            responses: number;
            /** Input */
            input: number;
            /** Cache Write 5M */
            cache_write_5m: number;
            /** Cache Write 1H */
            cache_write_1h: number;
            /** Cache Read */
            cache_read: number;
            /** Output */
            output: number;
            /** Thinking */
            thinking: number;
            /** Web Searches */
            web_searches: number;
            /** Cost Usd */
            cost_usd: number;
            /**
             * Unpriced
             * @default 0
             */
            unpriced: number;
        };
        /** ConciergeOut */
        ConciergeOut: {
            /** Project */
            project: string;
            /** Text */
            text: string;
            /** Notes */
            notes: string[];
        };
        /** DismissFindingIn */
        DismissFindingIn: {
            /**
             * Dismissed
             * @default true
             */
            dismissed: boolean;
        };
        /** DismissFindingOut */
        DismissFindingOut: {
            /** Id */
            id: string;
            /** Dismissed */
            dismissed: boolean;
        };
        /** FindingOut */
        FindingOut: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "anomaly" | "cache" | "tip" | "waste" | "peak" | "context";
            /** Rule */
            rule: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "urgent";
            /** Subject */
            subject: string;
            /** Day */
            day: string | null;
            /** Title */
            title: string;
            /** Detail */
            detail: string;
            /** Coverage */
            coverage: string;
            /** Session Id */
            session_id: string | null;
            /** Savings Usd */
            savings_usd: number | null;
            /** Metrics */
            metrics: {
                [key: string]: number | string | null;
            };
            /** Dismissed */
            dismissed: boolean;
            /** Created At */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HarvestResultOut */
        HarvestResultOut: {
            /** Written */
            written: number;
            /** Skipped */
            skipped: number;
        };
        /** HealthOut */
        HealthOut: {
            /** Turns */
            turns: {
                [key: string]: unknown;
            };
            /** Cloud */
            cloud: {
                [key: string]: unknown;
            };
            /** Cloud By Surface */
            cloud_by_surface: {
                [key: string]: unknown;
            }[];
            /** Prompts */
            prompts: {
                [key: string]: unknown;
            };
            /** Last Harvest */
            last_harvest: string | null;
            /** Note */
            note: string;
        };
        /** QuotaOut */
        QuotaOut: {
            /** Source */
            source: string;
            /** Fetched At */
            fetched_at: string;
            /** Windows */
            windows: components["schemas"]["WindowOut"][];
        };
        /** ServiceStatusOut */
        ServiceStatusOut: {
            /** Indicator */
            indicator: string;
            /** Description */
            description: string;
            /** Url */
            url: string;
        };
        /** SessionDetailOut */
        SessionDetailOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Surface */
            surface: string | null;
            /** Project */
            project: string | null;
            /** Model */
            model: string | null;
            /** Started */
            started: string | null;
            /** Ended */
            ended: string | null;
            /** Tokens */
            tokens: number;
            /** Cost */
            cost: number;
            /** Harvested */
            harvested: boolean;
            /** Cursor */
            cursor?: string | null;
            /**
             * Unpriced Turns
             * @default 0
             */
            unpriced_turns: number;
            /** Context Used */
            context_used?: number | null;
            /** Context Max */
            context_max?: number | null;
            /** Turns */
            turns: components["schemas"]["TurnOut"][];
        };
        /** SessionFacetsOut */
        SessionFacetsOut: {
            /** Sources */
            sources: string[];
            /** Projects */
            projects: string[];
            /** Models */
            models: string[];
        };
        /** SessionOut */
        SessionOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Surface */
            surface: string | null;
            /** Project */
            project: string | null;
            /** Model */
            model: string | null;
            /** Started */
            started: string | null;
            /** Ended */
            ended: string | null;
            /** Tokens */
            tokens: number;
            /** Cost */
            cost: number;
            /** Harvested */
            harvested: boolean;
            /** Cursor */
            cursor?: string | null;
            /**
             * Unpriced Turns
             * @default 0
             */
            unpriced_turns: number;
            /** Context Used */
            context_used?: number | null;
            /** Context Max */
            context_max?: number | null;
        };
        /** SummaryOut */
        SummaryOut: {
            total: components["schemas"]["BucketOut"];
            /** By Day */
            by_day: {
                [key: string]: components["schemas"]["BucketOut"];
            };
            /** By Model */
            by_model: {
                [key: string]: components["schemas"]["BucketOut"];
            };
            /** By Source */
            by_source: {
                [key: string]: components["schemas"]["BucketOut"];
            };
            /** By Project */
            by_project: {
                [key: string]: components["schemas"]["BucketOut"];
            };
            /** By Day Model */
            by_day_model: {
                [key: string]: components["schemas"]["BucketOut"];
            };
            /** By Hour */
            by_hour: {
                [key: string]: components["schemas"]["BucketOut"];
            };
            /** Sessions */
            sessions: number;
            /** Unknown Models */
            unknown_models: string[];
            /** Restored Days */
            restored_days: string[];
            /** Cache Hit Rate */
            cache_hit_rate: number;
            active_block?: components["schemas"]["ActiveBlockOut"] | null;
        };
        /** SyncResultOut */
        SyncResultOut: {
            /** Parsed */
            parsed: number;
            /** Skipped */
            skipped: number;
            /** Turns */
            turns: number;
            /** Duplicates */
            duplicates: number;
            /** Prompts */
            prompts: number;
        };
        /** TurnOut */
        TurnOut: {
            /** Msg Id */
            msg_id: string;
            /** Request Id */
            request_id: string;
            /** Ts */
            ts: string;
            /** Day */
            day: string;
            /** Source */
            source: string;
            /** Project */
            project: string;
            /** Model */
            model: string;
            /** Input */
            input: number;
            /** Cache 5M */
            cache_5m: number;
            /** Cache 1H */
            cache_1h: number;
            /** Cache Read */
            cache_read: number;
            /** Output */
            output: number;
            /** Thinking */
            thinking: number;
            /** Web Search */
            web_search: number;
            /** Sidechain */
            sidechain: number;
            /** Fast */
            fast: number;
            /** Geo */
            geo: string | null;
            /** Cost */
            cost: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeeklySummaryOut */
        WeeklySummaryOut: {
            /** Status */
            status: string;
            /** Text */
            text: string | null;
            /** Detail */
            detail: string;
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
        };
        /** WindowOut */
        WindowOut: {
            /** Label */
            label: string;
            /** Utilization */
            utilization: number;
            /** Resets At */
            resets_at: string | null;
        };
        /** WrappedModelMonthOut */
        WrappedModelMonthOut: {
            /** Month */
            month: string;
            /** Model */
            model: string;
            /** Cost Usd */
            cost_usd: number;
            /** Tokens */
            tokens: number;
        };
        /** WrappedOut */
        WrappedOut: {
            /** Year */
            year: number;
            /** Timezone */
            timezone: string;
            local_summary: components["schemas"]["SummaryOut"];
            /** Stored Cost Usd */
            stored_cost_usd: number;
            /** Harvested Cost Usd */
            harvested_cost_usd: number;
            /** Stored Tokens */
            stored_tokens: number;
            /** Stored Sessions */
            stored_sessions: number;
            /** Unpriced Turns */
            unpriced_turns: number;
            /** Annual Plan Usd */
            annual_plan_usd: number | null;
            /** Api Equivalent Multiple */
            api_equivalent_multiple: number | null;
            /** Busiest Day */
            busiest_day: string | null;
            /** Busiest Hour */
            busiest_hour: number | null;
            /** Longest Streak */
            longest_streak: number;
            /** Top Projects */
            top_projects: components["schemas"]["WrappedProjectOut"][];
            /** Model Months */
            model_months: components["schemas"]["WrappedModelMonthOut"][];
            biggest_session: components["schemas"]["WrappedSessionOut"] | null;
            /** Cache Savings Usd */
            cache_savings_usd: number | null;
            /** Notes */
            notes: string[];
        };
        /** WrappedProjectOut */
        WrappedProjectOut: {
            /** Name */
            name: string;
            /** Cost Usd */
            cost_usd: number;
            /** Tokens */
            tokens: number;
        };
        /** WrappedSessionOut */
        WrappedSessionOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Cost Usd */
            cost_usd: number;
            /** Tokens */
            tokens: number;
            /** Harvested */
            harvested: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    wrapped_api_wrapped_get: {
        parameters: {
            query?: {
                year?: number | null;
                from?: string | null;
                to?: string | null;
                source?: string;
                project?: string | null;
                model?: string | null;
                metric?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WrappedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alerts_api_alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertsOut"];
                };
            };
        };
    };
    service_status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceStatusOut"] | null;
                };
            };
        };
    };
    weekly_summary_api_weekly_summary_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklySummaryOut"];
                };
            };
        };
    };
    concierge_api_concierge_get: {
        parameters: {
            query: {
                project: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConciergeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    findings_api_analysis_post: {
        parameters: {
            query?: {
                kind?: ("anomaly" | "cache" | "tip" | "waste" | "peak" | "context") | null;
                severity?: ("info" | "warning" | "urgent") | null;
                include_dismissed?: boolean;
                from?: string | null;
                to?: string | null;
                source?: string;
                project?: string | null;
                model?: string | null;
                metric?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    findings_api_findings_get: {
        parameters: {
            query?: {
                kind?: ("anomaly" | "cache" | "tip" | "waste" | "peak" | "context") | null;
                severity?: ("info" | "warning" | "urgent") | null;
                include_dismissed?: boolean;
                from?: string | null;
                to?: string | null;
                source?: string;
                project?: string | null;
                model?: string | null;
                metric?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_finding_api_findings__finding_id__dismiss_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DismissFindingIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DismissFindingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_summary_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                source?: string;
                project?: string | null;
                model?: string | null;
                metric?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daily_api_daily_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                source?: string;
                project?: string | null;
                model?: string | null;
                metric?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["BucketOut"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hourly_api_hourly_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                source?: string;
                project?: string | null;
                model?: string | null;
                metric?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["BucketOut"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    breakdown_api_breakdown__dim__get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                source?: string;
                project?: string | null;
                model?: string | null;
                metric?: string;
            };
            header?: never;
            path: {
                dim: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["BucketOut"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sessions_list_api_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                q?: string | null;
                from?: string | null;
                to?: string | null;
                source?: string;
                project?: string | null;
                model?: string | null;
                metric?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_detail_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_facets_api_session_facets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionFacetsOut"];
                };
            };
        };
    };
    blocks_api_blocks_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                source?: string;
                project?: string | null;
                model?: string | null;
                metric?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quota_endpoint_api_quota_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                source?: string;
                project?: string | null;
                model?: string | null;
                metric?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotaOut"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    sync_api_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResultOut"];
                };
            };
        };
    };
    harvest_api_harvest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HarvestResultOut"];
                };
            };
        };
    };
    export_api_export_get: {
        parameters: {
            query?: {
                format?: string;
                from?: string | null;
                to?: string | null;
                source?: string;
                project?: string | null;
                model?: string | null;
                metric?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    legacy_usage_api_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    legacy_dataset_api_dataset_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    legacy_page_index_html_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    legacy_page__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
}
