-- Synthetic vibewatt 0.3.0/schema 9 store. No developer data.
-- Schema generated by store.connect() from git 11f83d9:vibewatt/store.py,
-- loaded as vibewatt.legacy_store against the current package in ignored scratch.
-- Rows use old upsert_turns(), rebuild_rollup(), upsert_titles() and
-- upsert_cloud_sessions(); history_days and user_keep are synthetic SQL rows.
-- Standard Opus 5 rates are unchanged; cloud cost is deliberately source-reported.
BEGIN TRANSACTION;
CREATE TABLE dismissals (key TEXT PRIMARY KEY, at TEXT);
CREATE TABLE files (
      path        TEXT PRIMARY KEY,
      mtime       REAL NOT NULL,
      size        INTEGER NOT NULL,
      parsed_at   TEXT NOT NULL,
      turn_count  INTEGER NOT NULL DEFAULT 0
    , dropped TEXT);
CREATE TABLE findings (
      id TEXT PRIMARY KEY, scope TEXT NOT NULL, kind TEXT NOT NULL,
      severity TEXT NOT NULL, day TEXT, subject TEXT NOT NULL,
      detail_json TEXT NOT NULL, created_at TEXT NOT NULL,
      dismissed INTEGER NOT NULL DEFAULT 0, active INTEGER NOT NULL DEFAULT 1
    );
CREATE TABLE history_days (
      day TEXT NOT NULL, model TEXT NOT NULL,
      responses INTEGER NOT NULL DEFAULT 0, input INTEGER NOT NULL DEFAULT 0,
      cache_5m INTEGER NOT NULL DEFAULT 0, cache_1h INTEGER NOT NULL DEFAULT 0,
      cache_read INTEGER NOT NULL DEFAULT 0, output INTEGER NOT NULL DEFAULT 0,
      thinking INTEGER NOT NULL DEFAULT 0, web_search INTEGER NOT NULL DEFAULT 0,
      cost REAL,
      PRIMARY KEY (day, model)
    );
INSERT INTO "history_days" VALUES('2026-09-14','claude-opus-5',3,61,13,7,43,67,0,0,0.5);
CREATE TABLE meta (key TEXT PRIMARY KEY, value TEXT);
INSERT INTO "meta" VALUES('sync_tz','schema-5');
INSERT INTO "meta" VALUES('schema','9');
INSERT INTO "meta" VALUES('last_harvest','2026-09-15T17:30:00+00:00');
CREATE TABLE quota_samples (
      ts          TEXT NOT NULL,
      key         TEXT NOT NULL,
      label       TEXT NOT NULL,
      scope       TEXT NOT NULL,
      utilization REAL NOT NULL,
      resets_at   TEXT,
      source      TEXT NOT NULL,
      PRIMARY KEY (ts, key, scope)
    );
CREATE TABLE raw_lines (
      path TEXT NOT NULL, source TEXT NOT NULL, hr TEXT NOT NULL, session TEXT NOT NULL,
      messages INTEGER NOT NULL, tokens INTEGER NOT NULL,
      PRIMARY KEY (path, hr, session)
    );
CREATE TABLE rollup (
      hr TEXT NOT NULL, day TEXT NOT NULL, hour INTEGER,
      source TEXT NOT NULL, project TEXT NOT NULL, model TEXT NOT NULL,
      session TEXT NOT NULL, sidechain INTEGER NOT NULL,
      responses INTEGER NOT NULL, input INTEGER NOT NULL, cache_5m INTEGER NOT NULL,
      cache_1h INTEGER NOT NULL, cache_read INTEGER NOT NULL, output INTEGER NOT NULL,
      thinking INTEGER NOT NULL, web_search INTEGER NOT NULL,
      cost REAL, unpriced INTEGER NOT NULL, first_ts TEXT NOT NULL, last_ts TEXT NOT NULL
);
INSERT INTO "rollup" VALUES('2026-09-15T18','2026-09-15',18,'claude-code','legacy-demo','claude-opus-5','legacy-local',0,1,101,17,19,23,29,7,2,0.02153775,0,'2026-09-15T18:00:00+00:00','2026-09-15T18:00:00+00:00');
INSERT INTO "rollup" VALUES('2026-09-15T19','2026-09-15',19,'claude-code','legacy-demo','legacy-unknown-model','legacy-local',0,1,37,0,0,0,11,0,0,NULL,1,'2026-09-15T19:00:00+00:00','2026-09-15T19:00:00+00:00');
CREATE TABLE sessions (
  id          TEXT PRIMARY KEY,
  title       TEXT,
  origin      TEXT,                -- web_claude_ai | claude_code_cli | cowork-* | local
  surface     TEXT,                -- claude-code | cowork | web
  project     TEXT,
  model       TEXT,
  started     TEXT,
  ended       TEXT,
  input       INTEGER DEFAULT 0,
  cache_write INTEGER DEFAULT 0,
  cache_read  INTEGER DEFAULT 0,
  output      INTEGER DEFAULT 0,
  cost        REAL DEFAULT 0,
  context_used   INTEGER,
  context_max    INTEGER,
  harvested   INTEGER NOT NULL DEFAULT 0,   -- 1 = came from the session API
  raw         TEXT
);
INSERT INTO "sessions" VALUES('legacy-cloud','Synthetic harvested title','web_claude_ai','web',NULL,'claude-opus-5','2026-09-15T17:00:00+00:00','2026-09-15T17:30:00+00:00',503,31,47,59,12.345,NULL,NULL,1,'{"id":"legacy-cloud","title":"Synthetic harvested title","origin":"web_claude_ai","environment_kind":"anthropic_cloud","created_at":"2026-09-15T17:00:00+00:00","updated_at":"2026-09-15T17:30:00+00:00","session_context":{"model":"claude-opus-5"},"external_metadata":{"usage":{"input_tokens":503,"cache_write_tokens":31,"cache_read_tokens":47,"output_tokens":59,"cost_usd":12.345}}}');
CREATE TABLE titles (
  session   TEXT PRIMARY KEY,
  kind      TEXT NOT NULL,
  rank      INTEGER NOT NULL,
  ts        TEXT,
  text      TEXT NOT NULL
);
INSERT INTO "titles" VALUES('legacy-local','custom-title',4,'2026-09-15T18:00:00+00:00','Synthetic 日本語 legacy title');
CREATE TABLE tool_read_files (
      path TEXT PRIMARY KEY, mtime REAL NOT NULL, size INTEGER NOT NULL
    );
CREATE TABLE tool_reads (
      session TEXT NOT NULL, tool_id TEXT NOT NULL, ts TEXT NOT NULL,
      source TEXT NOT NULL, project TEXT NOT NULL, model TEXT NOT NULL,
      path_hash TEXT NOT NULL, PRIMARY KEY(session, tool_id)
    );
CREATE TABLE turns (
  msg_id      TEXT NOT NULL,
  request_id  TEXT NOT NULL,
  ts          TEXT NOT NULL,       -- ISO 8601 UTC
  day         TEXT NOT NULL,       -- local date, precomputed for grouping
  source      TEXT NOT NULL,       -- claude-code | cowork
  project     TEXT NOT NULL,
  session     TEXT NOT NULL,
  model       TEXT NOT NULL,
  input       INTEGER NOT NULL DEFAULT 0,
  cache_5m    INTEGER NOT NULL DEFAULT 0,
  cache_1h    INTEGER NOT NULL DEFAULT 0,
  cache_read  INTEGER NOT NULL DEFAULT 0,
  output      INTEGER NOT NULL DEFAULT 0,
  thinking    INTEGER NOT NULL DEFAULT 0,
  web_search  INTEGER NOT NULL DEFAULT 0,
  sidechain   INTEGER NOT NULL DEFAULT 0,
  fast        INTEGER NOT NULL DEFAULT 0,
  geo         TEXT,
  cost        REAL, version TEXT, hour INTEGER,
  PRIMARY KEY (msg_id, request_id)
);
INSERT INTO "turns" VALUES('legacy-priced','legacy-request-1','2026-09-15T18:00:00+00:00','2026-09-15','claude-code','legacy-demo','legacy-local','claude-opus-5',101,17,19,23,29,7,2,0,0,NULL,0.02153775,'2.1.0',18);
INSERT INTO "turns" VALUES('legacy-unpriced','legacy-request-2','2026-09-15T19:00:00+00:00','2026-09-15','claude-code','legacy-demo','legacy-local','legacy-unknown-model',37,0,0,0,11,0,0,0,0,NULL,NULL,'2.1.0',19);
CREATE TABLE user_keep (id INTEGER PRIMARY KEY, note TEXT NOT NULL);
INSERT INTO "user_keep" VALUES(1,'Synthetic custom table must survive');
CREATE INDEX turns_day ON turns(day);
CREATE INDEX turns_session ON turns(session);
CREATE INDEX turns_model ON turns(model);
CREATE INDEX sessions_started ON sessions(started);
CREATE INDEX findings_scope ON findings(scope, active);
CREATE INDEX turns_hr ON turns(substr(ts, 1, 13));
CREATE INDEX rollup_day ON rollup(day);
CREATE INDEX rollup_hr ON rollup(hr);
CREATE INDEX quota_samples_series ON quota_samples(key, scope, ts);
CREATE INDEX raw_lines_hr ON raw_lines(hr);
COMMIT;
